import { GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import EForm from "../component/Form";
import { fetchEForms } from "../utils/fetchEForm";

import { EForms } from '../types/typings'

type Props = {
  eFromData: EForms[]
}

const Home = ({eFromData}: Props) => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b bg-white p-2">
        <EForm eFromData={eFromData} />
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const eFromData = await fetchEForms()

  return {
    props: {
      eFromData
    }
  }
}