import type { GetStaticProps } from "next";
import Head from "next/head";

import EForm from "../component/Form";
import type { EForms } from '../types/typings'
import { fetchEForms } from "../utils/fetchEForm";

import { FormProvider } from '../utils/FormContext'

type Props = {
  eFromData: EForms[]
}

const Home = ({eFromData}: Props) => {
  return (
    <>
      <Head>
        <title>Economic Responsive Form</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b bg-white p-2">
        <FormProvider>
          <EForm eFromData={eFromData} />
        </FormProvider>
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const eFromData = await fetchEForms()

  return {
    props: {
      eFromData
    }
  }
}